[toolchain]
channel = "stable"
components = [ "rustfmt", "rustc", "rust-analyzer", "clippy", "rust-src", "rust-std" ]
targets = [ "wasm32-unknown-unknown", "x86_64-unknown-linux-gnu" ]
profile = "default"
